# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
title: licenseplate
email: code@mweiss.ch
description: >- # this means to ignore newlines until "baseurl:"
  A browser extension aiming to help you to detect insufficiently
  licensed code on github.
baseurl: /licenseplate # the subpath of your site, e.g. /blog
url: miweiss.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Aux links for the upper right navigation
aux_links:
  "Sources On GitHub":
    - "//github.com/miweiss/licenseplate"

footer_content: "Copyright Michael Weiss. Distributed by an <a href=\"https://github.com/MiWeiss/licenseplate/blob/main/LICENSE\">MIT license.</a>"

color_scheme: dark

logo: "licenseplate.png"